
const $ = s => document.querySelector(s);
let data, current, timerId, startedAt, elapsed = 0, running = false, mode = 'stopwatch', remaining = 0;
const DB_NAME='simplefit-db', STORE='logs';
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function addLog(log){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(log);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});}
async function getLogs(){const db=await openDb();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));r.onerror=()=>rej(r.error);});}
async function replaceLogs(logs){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');const st=tx.objectStore(STORE);st.clear();logs.forEach(l=>st.put(l));tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});}
function fmt(sec){sec=Math.max(0,Math.floor(sec));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function renderLevels(){const level=$('#level'); level.innerHTML=data.programs.beginner.levels.map(l=>`<option value="${l.level}">Level ${l.level}</option>`).join('');}
function renderWorkout(){const program=$('#program').value; $('#level-wrap').style.display=program==='tabata'?'none':''; $('#day-wrap').style.display=program==='tabata'?'none':'';
 if(program==='tabata'){current={program:'tabata',type:'tabata',title:'Tabata · 32 intervals',work:data.tabata.intervals.flatMap(s=>Array.from({length:s.rounds},(_,i)=>({exercise:s.exercise,reps:`20s work / 10s rest #${i+1}`})))}; mode='countdown'; remaining=32*30 + 3*60;}
 else{const lvl=+$('#level').value, day=+$('#day').value; const level=data.programs.beginner.levels.find(l=>l.level===lvl); current={...level.days[day-1],program:'beginner',level:lvl,title:`Beginner level ${lvl} · Day ${day}`}; mode=current.type==='amrap'?'countdown':'stopwatch'; remaining=current.durationSeconds||0;}
 elapsed=0; running=false; clearInterval(timerId); $('#startPause').textContent='Start'; $('#workoutTitle').textContent=current.title; $('#workoutType').textContent=current.label || current.type; $('#timer').textContent=mode==='countdown'?fmt(remaining):'00:00'; $('#exerciseList').innerHTML=current.work.map(x=>`<div class="exercise-item"><strong>${x.exercise}</strong><span>${x.reps} ${Number.isFinite(x.reps)?'reps':''}</span></div>`).join(''); localStorage.setItem('simplefit.lastSelection', JSON.stringify({program,$level:$('#level').value,day:$('#day').value}));}
function tick(){const diff=Math.floor((Date.now()-startedAt)/1000); if(mode==='countdown'){const left=remaining-diff; $('#timer').textContent=fmt(left); if(left<=0){clearInterval(timerId);running=false;$('#startPause').textContent='Done'; if(navigator.vibrate) navigator.vibrate([200,100,200]);}} else $('#timer').textContent=fmt(elapsed+diff);}
function startPause(){if(!current) renderWorkout(); if(running){elapsed += Math.floor((Date.now()-startedAt)/1000); clearInterval(timerId); running=false; $('#startPause').textContent='Resume';} else {startedAt=Date.now(); timerId=setInterval(tick,250); running=true; $('#startPause').textContent='Pause'; tick();}}
async function finish(){if(!current) return; if(running) startPause(); const duration = mode==='countdown' ? (current.durationSeconds || remaining) : elapsed; const log={id:new Date().toISOString(),createdAt:new Date().toISOString(),program:current.program,level:current.level||null,day:current.day||null,type:current.type,title:current.title,durationSeconds:duration,roundsCompleted:+$('#rounds').value||0,score:$('#score').value.trim(),notes:$('#notes').value.trim()}; await addLog(log); $('#rounds').value=0; $('#score').value=''; $('#notes').value=''; await renderHistory();}
async function renderHistory(){const logs=await getLogs(); $('#history').innerHTML=logs.length?logs.map(l=>`<div class="history-item"><strong>${new Date(l.createdAt).toLocaleString()}</strong><br>${l.title}<br><span class="muted">${l.score || (l.roundsCompleted?l.roundsCompleted+' rounds':'completed')}${l.notes?' · '+l.notes:''}</span></div>`).join(''):'<p class="muted">No workouts saved yet.</p>';}
async function init(){data=await fetch('data/workouts.json').then(r=>r.json()); renderLevels(); const last=JSON.parse(localStorage.getItem('simplefit.lastSelection')||'{}'); if(last.program) $('#program').value=last.program; if(last.$level) $('#level').value=last.$level; if(last.day) $('#day').value=last.day; renderWorkout(); await renderHistory();}
$('#loadWorkout').onclick=renderWorkout; $('#program').onchange=renderWorkout; $('#level').onchange=renderWorkout; $('#day').onchange=renderWorkout; $('#startPause').onclick=startPause; $('#reset').onclick=renderWorkout; $('#finish').onclick=finish;
$('#exportData').onclick=async()=>{const logs=await getLogs(); const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),logs},null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='simplefit-history.json'; a.click(); URL.revokeObjectURL(a.href);};
$('#importData').onchange=async e=>{const f=e.target.files[0]; if(!f)return; const obj=JSON.parse(await f.text()); await replaceLogs(obj.logs||[]); await renderHistory();};
init().catch(err=>{console.error(err); document.body.insertAdjacentHTML('afterbegin',`<p class="notice danger">App failed to load: ${err.message}</p>`)});
